apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ueransim.name" .}}-gnb
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/component: gnb
    {{- include "ueransim.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "ueransim.selectorLabels" . | nindent 6 }}

  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gnb
        {{- include "ueransim.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: envsubst
          image: bhgedigital/envsubst
          args:
            - sh
            - -c
            - cat /configs/gnb.yaml | envsubst > /configs-new/gnb.yaml
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /configs/
            - name: config-subs
              mountPath: /configs-new/

      containers:
        - name: {{ include "ueransim.name" . }}-gnb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "./nr-gnb"
          args:
            - "-c"
            - "/configs/gnb.yaml"
          ports:
            {{- toYaml .Values.gnbPorts | nindent 12 }}


          {{- if .Values.resources }}
          resources: {{- toYaml .Values.gnbResources | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: config-subs
              mountPath:  /configs/

      volumes:
        - name: config-subs
          emptyDir: { }
        - name: config
          configMap:
            name: {{ include "ueransim.name" .}}-configmap-gnb
