apiVersion: v1
kind: Service
metadata:
  name: {{ include "ueransim.name" . }}-gnb
  namespace: {{ .Values.namespace | quote}}
  labels: {{- include "ueransim.labels" . | nindent 4 }}
    app.kubernetes.io/component: gnb
spec:
  ports:
  - name: gnb-ue
    port: 4997
    protocol: UDP
{{/*  - name: gnb-upf*/}}
{{/*    port: 2152*/}}
{{/*    protocol: UDP*/}}
  publishNotReadyAddresses: true
  selector:
    {{- include "ueransim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gnb