apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ueransim.name" .}}-configmap-ue
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/component: ue
    {{- include "ueransim.labels" . | nindent 4 }}
data:
  ue.yaml: |
    {{ toYaml .Values.ueConfig | nindent 4 }}