apiVersion: v2
name: open5gs-5gcore
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-amf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-ausf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-nrf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-bsf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-smf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-upf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-udm
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-udr
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-pcf
    repository: "file://../open5gs-component-base"

  - name: open5gs-component-base
    version: 0.1.0
    alias: open5gs-nssf
    repository: "file://../open5gs-component-base"

  - name: mongodb
    version: ~12.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
#
#  - name: open5gs-webui
#    version: 0.1.0
#    repository: "file://../open5gs-webui"