apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: {{ .Values.namespace | quote}}
  labels:
    {{- include "open5gs-webui.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "open5gs-webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open5gs-webui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DB_URI
              value: "mongodb://open5gs-mongodb/open5gs"
            - name: HOSTNAME
              value: 0.0.0.0
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
